adminUser:
  password: vault:llamarune/adminUser:password
  username: admin
dashboardUrl: https://dashboard.play-jxaas.live
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:llamarune/pipelineUser:token
  username: cloudbees-ci-cd-play[bot]
prow:
  hmacToken: vault:llamarune/prow:hmacToken
segmentWriteKey: vault:llamarune:segmentWriteKey
